### Q1- Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

In [2]:
print('\033[1m' + '----------------- Input Values -----------------' + '\033[0m')

Input_array = np.array([3,5,7,2])
no_of_col = 5
incresing = True


print('\nInput array \t\t: ',Input_array)
print('Number of columns \t: ',no_of_col)
print('incresing \t\t: ',incresing)
print('\n')


#----------------------------------------------------------
def Output_matrix(Input_array, no_of_col, incresing = True):
    if incresing:
        Result =  np.array([i**j for i in Input_array for j in range(no_of_col)]).reshape(len(Input_array),no_of_col)
    else:
        Result = np.array([i**(no_of_col-1-j) for i in Input_array for j in range(no_of_col)]).reshape(len(Input_array),no_of_col)
    return Result

Result_op_matrix = Output_matrix(Input_array, no_of_col, False)
Result_op_matrix

print('\033[1m' + '------------- Result of output Values -------------' + '\033[0m\n')

print(Result_op_matrix)

----------------- Input Values -----------------

Input array 		:  [3 5 7 2]
Number of columns 	:  5
incresing 		:  True


------------- Result of output Values -------------

[[  81   27    9    3    1]
 [ 625  125   25    5    1]
 [2401  343   49    7    1]
 [  16    8    4    2    1]]


### Q2-

### Problem Statement 2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
def Moving_avg_array(Values,Window_size):
    Result = []
    Moving_avg = len(Values) - Window_size  + 1
    for i in range(Moving_avg):
        Result.append(Values[i:i+Window_size].sum()/Window_size)
    return Result

In [5]:
# Testing
Values = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
Window_size = 4

print('\033[1m' + '----------------- Input Values -----------------' + '\033[0m\n')
print('Given values are : ', Values)
print('Window size : ', Window_size)


print('\n\033[1m' + '------------- Result of output Values -------------' + '\033[0m\n')

print(Moving_avg_array(Values, Window_size))

----------------- Input Values -----------------

Given values are :  [ 10  20  30  40  50  60  70  80  90 100]
Window size :  4

------------- Result of output Values -------------

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]


In [6]:
# Testing 2
Values = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
Window_size = 3

print('\033[1m' + '----------------- Input Values -----------------' + '\033[0m\n')
print('Given values are : ', Values)
print('Window size : ', Window_size)


print('\n\033[1m' + '------------- Result of output Values -------------' + '\033[0m\n')

print(Moving_avg_array(Values,Window_size))

----------------- Input Values -----------------

Given values are :  [  3   5   7   2   8  10  11  65  72  81  99 100 150]
Window size :  3

------------- Result of output Values -------------

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
